### ISSUE TITLE
Appium 1.5

### ISSUE THREAD

**Issue by tzedar** [jollychang/robotframework-appiumlibrary#102]
Is there any support being worked on for Appium 1.5 which just came out last week?

**Comment by serhatbolsu** [comment]
Ideally library already supports 1.5 since Appium 1.5 claims that they did not change and functional code. Maybe `desired_capability` changes might effect. Can you test and make a pull request if you find not working parts ?

**Comment by semutmerah** [comment]
There is an issue for Scroll To keywords, because they removed the scrollTo capability for mobile.

The workaround for this is change the scroll_to method to:
`driver.execute_script("mobile: scroll", {"direction": 'down', 'element': el})`
You can change the direction to up/down

I already make this change on my local, but I don't know how to make it backward compatible.

**Comment by tzedar** [comment]
My issue is with the desired_capability flag. Has anyone used it and how did it work?

**Comment by serhatbolsu** [comment]
@tzedar We been using 1.5.2 with various test cases, there seems to be no problem overall. 

@semutmerah if you see any problem, please submit a pull request with an simple explanation or you could wait until other people need it and fix it.

**Comment by serhatbolsu** [comment]
About `desired_capability`please explain it in detail in another issue. I am marking this as resolved
